### ISSUE TITLE
Handle issue/redeem requests in indexer

### ISSUE THREAD

**Issue by annatekl** [pendulum-chain/pendulum-squids#66]
#### Context
There is a problem with the transaction times displayed in "Spacewalk > Transfers" on the Pendulum portal. The times change every 10-12 seconds due to the automatic table refresh with each new block in the chain. The estimateRequestCreationTime function estimates the transaction time based on a 12-second interval between blocks, but since blocks do not appear exactly every 12 seconds, the estimated transaction time fluctuates.

Issue:
- The transaction time changes from, for example, 10:44:23 to 10:44:42 after an automatic refresh for the same transaction.

#### Requirements
- [ ] Implement the feature to handle issue/redeem requests in the indexer.
- [ ] Ensure the indexer includes the necessary metadata: on-chain data and the creation timestamp of requests.
- [ ] Modify the portal to use this new data from the indexer for consistent timestamps.

**Comment by annatekl** [comment]
@ebma is there any technical details missing?

**Comment by ebma** [comment]
The last step, ie. 'Modify the portal to use this new data from the indexer for consistent timestamps.' would then need to be happen as a follow-up to this task and is actually not something we would do as part of this ticket. But the rest looks good. Since there already is a ticket for this in the portal repository, please remove that last item from the 'Requirements' section of this ticket and add a link to the portal ticket as a zenhub dependency @annatekl. 

The rest looks good 👍

**Comment by annatekl** [comment]
@ebma what ticket on the portal are you referring too? the bug ticket?

**Comment by ebma** [comment]
Yes, this one https://github.com/pendulum-chain/portal/issues/447.

**Comment by prayagd** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Pendulum-6408a0365cda59c57d39bee5/issues/pendulum-chain/pendulum-squids/66?planning-poker) with Zenhub @TorstenStueber @gianfra-t @ebma @bogdanS98

**Comment by TorstenStueber** [comment]
Just to make sure there are no misunderstanding: how do we define the "the creation timestamp of requests"? I assume it is the timestamp of the block that contains the request transaction?

**Comment by ebma** [comment]
Yes, let's use that.
